"""added status, place, point, direction, accrual

Revision ID: 2b1f3503d946
Revises: d64136f673a0
Create Date: 2025-04-06 02:19:23.850300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1f3503d946'
down_revision: Union[str, None] = 'd64136f673a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direction_id'), 'direction', ['id'], unique=False)
    op.create_table('place_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_type_id'), 'place_type', ['id'], unique=False)
    op.create_table('point_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_type_id'), 'point_type', ['id'], unique=False)
    op.create_table('status_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_type_id'), 'status_type', ['id'], unique=False)
    op.create_table('type_accrual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_accrual_id'), 'type_accrual', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_type_accrual_id'), table_name='type_accrual')
    op.drop_table('type_accrual')
    op.drop_index(op.f('ix_status_type_id'), table_name='status_type')
    op.drop_table('status_type')
    op.drop_index(op.f('ix_point_type_id'), table_name='point_type')
    op.drop_table('point_type')
    op.drop_index(op.f('ix_place_type_id'), table_name='place_type')
    op.drop_table('place_type')
    op.drop_index(op.f('ix_direction_id'), table_name='direction')
    op.drop_table('direction')
    # ### end Alembic commands ###
