"""Fix ReferralsModel relationship

Revision ID: 7fe5215a4d64
Revises: ad021ae842ee
Create Date: 2025-04-07 00:36:01.738015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe5215a4d64'
down_revision: Union[str, None] = 'ad021ae842ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direction_id'), 'direction', ['id'], unique=False)
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gender_id'), 'gender', ['id'], unique=False)
    op.create_table('place_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_type_id'), 'place_type', ['id'], unique=False)
    op.create_table('point_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_type_id'), 'point_type', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('duration', sa.TIMESTAMP(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('status_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_type_id'), 'status_type', ['id'], unique=False)
    op.create_table('type_accrual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_accrual_id'), 'type_accrual', ['id'], unique=False)
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('id_gender', sa.Integer(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_gender'], ['gender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('added_points', sa.Float(), nullable=True),
    sa.Column('id_gender', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_gender'], ['gender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('client_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('permanent_points', sa.Float(), nullable=True),
    sa.Column('temporary_points', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_balances_id'), 'client_balances', ['id'], unique=False)
    op.create_table('point_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('id_point_type', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('id_direction', sa.Integer(), nullable=True),
    sa.Column('id_type_accural', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.ForeignKeyConstraint(['id_direction'], ['direction.id'], ),
    sa.ForeignKeyConstraint(['id_point_type'], ['point_type.id'], ),
    sa.ForeignKeyConstraint(['id_type_accural'], ['type_accrual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_logs_id'), 'point_logs', ['id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('referral_phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_table('make_appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('id_address', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('id_status_type', sa.Integer(), nullable=True),
    sa.Column('final_sum', sa.Float(), nullable=True),
    sa.Column('id_services', sa.Integer(), nullable=True),
    sa.Column('id_place_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_address'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.ForeignKeyConstraint(['id_place_type'], ['place_type.id'], ),
    sa.ForeignKeyConstraint(['id_services'], ['services.id'], ),
    sa.ForeignKeyConstraint(['id_status_type'], ['status_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_make_appointment_id'), 'make_appointment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_make_appointment_id'), table_name='make_appointment')
    op.drop_table('make_appointment')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_point_logs_id'), table_name='point_logs')
    op.drop_table('point_logs')
    op.drop_index(op.f('ix_client_balances_id'), table_name='client_balances')
    op.drop_table('client_balances')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_type_accrual_id'), table_name='type_accrual')
    op.drop_table('type_accrual')
    op.drop_index(op.f('ix_status_type_id'), table_name='status_type')
    op.drop_table('status_type')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_point_type_id'), table_name='point_type')
    op.drop_table('point_type')
    op.drop_index(op.f('ix_place_type_id'), table_name='place_type')
    op.drop_table('place_type')
    op.drop_index(op.f('ix_gender_id'), table_name='gender')
    op.drop_table('gender')
    op.drop_index(op.f('ix_direction_id'), table_name='direction')
    op.drop_table('direction')
    # ### end Alembic commands ###
